<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="simple_rover">

  <!-- Define xacro properties for wheels -->
  <xacro:property name="wheel_radius" value="0.3"/>
  <xacro:property name="wheel_width" value="0.25"/>
  <xacro:property name="wheel_separation" value="0.5"/>

  <xacro:include filename="$(find simulation)/urdf/camera.urdf.xacro"/>
  <xacro:normal_camera robot_name="rover"/>
  

  <gazebo reference="base_link">
    <material>Gazebo/White</material>
    <mu1>0.2</mu1>
    <mu2>0.2</mu2>
  </gazebo>

  <gazebo reference="right_wheel">
    <material>Gazebo/Red</material>
    <mu1>0.84</mu1>
    <mu2>0.84</mu2>
  </gazebo>

  <gazebo reference="left_wheel">
    <material>Gazebo/Red</material>
    <mu1>0.84</mu1>
    <mu2>0.84</mu2>
  </gazebo>

  <gazebo reference="caster_wheel">
    <material>Gazebo/Black</material>
    <mu1>0.0</mu1>
    <mu2>0.0</mu2>
  </gazebo>

  <gazebo reference="camera_link">
    <material>Gazebo/Blue</material>
  </gazebo>

  <link name="base_link">
    <visual>
      <geometry>
      <box size="1.0 0.5 0.3"/>
      </geometry>
    </visual>

    <collision>
      <geometry>
      <box size="1.0 0.5 0.3"/>
      </geometry> 
    </collision>

    <inertial>
      <mass value="1"/>
      <inertia ixx="0.166667" ixy="0" ixz="0" iyy="0.166667" iyz="0" izz="0.166667"/>
    </inertial>
  </link>

  <link name="left_wheel">
    <visual>
      <geometry>
      <cylinder radius="0.3" length="0.25"/>
      </geometry>
    </visual>

    <collision>
      <geometry>
      <cylinder radius="0.3" length="0.25"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="1"/>
      <inertia ixx="0.145833" ixy="0.0" ixz="0.0" iyy="0.145833" iyz="0.0" izz="0.125"/>
    </inertial>
  </link>

  <link name="right_wheel">
    <visual>
      <geometry>
      <cylinder radius="0.3" length="0.25"/>
      </geometry>
    </visual>

    <collision>
      <geometry>
      <cylinder radius="0.3" length="0.25"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="1"/>
      <inertia ixx="0.145833" ixy="0.0" ixz="0.0" iyy="0.145833" iyz="0.0" izz="0.125"/>
    </inertial>  
  </link>

  <link name="caster_wheel">
    <visual>
      <geometry>
      <sphere radius="0.2"/>
      </geometry>
    </visual>

    <collision>
      <geometry>
      <sphere radius="0.2"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="1"/>
      <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
    </inertial>  
  </link>

  <link name="camera_link">
    <visual>
      <geometry>
        <box size="0.01 0.01 0.01"/>
      </geometry>
    </visual>

    <collision>
      <geometry>
        <box size="0.01 0.01 0.01"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="0.01"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>
  </link>

  <joint name="joint_left" type="continuous">
    <parent link="base_link"/>
    <child link="left_wheel"/>
    <origin xyz="-0.25 0.375 0" rpy="1.5708 0 0"/>
    <axis xyz="0 0 -1"/>
    <dynamics friction="0.1"/>
  </joint>

  <joint name="joint_right" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel"/>
    <origin xyz="-0.25 -0.375 0" rpy="1.5708 0 0"/>
    <axis xyz="0 0 -1"/>
    <dynamics friction="0.1"/>
  </joint>

  <joint name="joint_caster_wheel" type="continuous">
    <parent link="base_link"/>
    <child link="caster_wheel"/>
    <origin xyz="0.25 0 -0.1" rpy="0 0 0"/>
    <dynamics friction="0.0"/>
  </joint>

  <joint name="camera_joint" type="fixed">
    <parent link="base_link"/>
    <child link="camera_link"/>
    <origin xyz="0.495 0 0.155" rpy="0 0 0"/>
  </joint>


  <gazebo>
    <plugin filename="gz-sim-diff-drive-system" name="gz::sim::systems::DiffDrive">
      <left_joint>joint_left</left_joint>
      <right_joint>joint_right</right_joint>
      <wheel_separation>${wheel_separation + wheel_width}</wheel_separation>
      <wheel_radius>${wheel_radius}</wheel_radius>
      <odom_publish_frequency>30</odom_publish_frequency>
      <max_wheel_torque>20</max_wheel_torque>
      <max_wheel_acceleration>1.0</max_wheel_acceleration>
      <topic>cmd_vel</topic>
      <odom_topic>odom</odom_topic>
      <frame_id>odom</frame_id>
      <child_frame_id>base_link</child_frame_id>
    </plugin>
  </gazebo>

  <gazebo>
    <plugin filename="gz-sim-sensors-system" name="gz::sim::systems::Sensors">
      <render_engine>ogre2</render_engine>
    </plugin>
  </gazebo>

</robot>